name: 'Deploy to Azure'
on:
  workflow_dispatch:   
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: '🧑‍🦱 Azure login'
        uses: azure/login@v2
        with:
          client-id: 1155c27d-f563-4b95-ab06-f9b9e935c347
          tenant-id: b1a8ac21-915f-4351-a075-b30346a974af
          subscription-id: dd1d9f582-ce04-4d4d-a490-ab247b746f7b

      - name: 'Deploy to Azure'
        run: |
          az deployment sub create \
            --name Deployment-$(date +"%Y-%m-%dT%H-%M-%S") \
            --template-file resource-group.bicep \
            --location westeurope \
            --parameters \
                location=westeurope \
      
          az deployment sub create \
            --name Deployment-$(date +"%Y-%m-%dT%H-%M-%S") \
            --template-file resources.bicep \
            --location westeurope \
            --parameters \
                location=westeurope \


                